---
title: "Datapaper WildCrossData Latin America"
number-sections: false
toc: false
editor: source
theme:
  light: flatly
  dark: superhero
---

### Welcome

This book documents the data quality checks performed on the camera trap data. Each chapter describes a specific check and its implementation.

### Chapters

2.  [Custom Functions](Quarto/00_presentation_functions.html) - Creates reusable custom functions for data checks.
3.  [Column Consistency](Quarto/01_column_consistency.html) - Checks for consistency in column types across spreadsheets.
4.  [Blank Cells](Quarto/02_blank_cells.html) - Identifies blank cells and sheets in the data.
5.  [Species Validity](Quarto/03_species.html) - Validates species names using the Global Names Verifier API.
6.  [Structure Checks](Quarto/04_structure.html) - Verifies consistency between camera trap and structure data
7.  [Camera ID Verification](Quarto/05_id_camera.html) - Ensures camera IDs are properly linked across datasets.
8.  [Camera Date Checks](Quarto/06_date.html) - Checks several possibilities for anomalous dates.
9.  [Camera ID Duplicated on Structure](Quarto/07_duplicated_ct.html) - Tests if there is a duplicated camera IDs for a given structure.
10. [Structure Measurements](Quarto/08_measurements.html) - Verifies the consistency of measurements fields.
11. [Structure Coordinates Parameters](Quarto/09_structure_coords_parameters.html) - Tests if the coordinates parameters such as UTM zones and parameters are correctly provided.
12. [Structure Locations](Quarto/10_structure_location.html) - Checks if the structures provided are within a distance of a road, railroad or pipeline.
13. [Structure Camera Record Criteria](Quarto/11_record_criteria.qmd) - Verifies if the records are comprised whithin the record criteria provided.

### About

This book is part of the data quality assurance process for the camera trap dataset. Each check is implemented in R and documented using Quarto.